# Site settings
title: LeGi
email: legisoftware@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Web developer, eCommerce developer, Web application developer, freelancer, website developer, Tigrinya dictionary, Tigrigna dictionary
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://legi.uk/" # the base hostname & protocol for your site
twitter_username: username
github_username: kiflay

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md


 
 